baseurl = "https://www.dddmelbourne.com"
DefaultContentLanguage = "en"
title = "DDD Melbourne"
metaDataFormat = "yaml"
googleAnalytics = "UA-99087610-1"

[Params]
  subtitle = "DDD Melbourne is a non profit community event run by developers for developers. Anyone can submit a session to the event and delegates then vote on the sessions they want to see."
  favicon = "images/favicon.ico"
  dateFormat = "Mon Jan 2, 2006"
  showDddByNight = true

[Author]
  name = "DDD Melbourne"
  email = "dddmelbourne@gmail.com"
  github = "OpenDDD"
  twitter = "dddmelb"
  instagram = "dddmelb"
  flickr = "photos/135717775@N07/"

[[menu.main]]
    name = "Blog"
    url = "https://blog.dddmelbourne.com/"
    weight = 7
